import Isotope.Submonad
import Isotope.Elgot
import Isotope.StreamAction
import Isotope.Binoidal.Category
import Isotope.Premonoidal.Category
import Isotope.Premonoidal.Braided
import Isotope.Premonoidal.Monoidal'
import Isotope.Effectful.Category
import Isotope.Effectful.Braided
import Isotope.WideSubcategory.Basic
import Isotope.WideSubcategory.Binoidal
import Isotope.WideSubcategory.Premonoidal
import Isotope.Substructural.Category
import Isotope.Utils.Wk
